name: adventofcode_2016
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'


# dependencies:
#   path: ^1.8.0

dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  format: ^1.1.1
  isolate: ^2.1.1
  stream_channel: ^2.1.0
  worker_manager: ^4.2.6
  convert: ^3.0.1 # Use the latest version available
  collection: ^1.18.0
